/* ============================================================
   Nexus Aetherial — real model dataset
   ----------------------------------------------------------------
   Figures are plausible, drawn from publicly-reported benchmark
   scores and product pages as of mid-2026. Treat as illustrative;
   the site is a design demonstration, not a live leaderboard.
   ============================================================ */

window.NEXUS_DATA = {
  models: [
    {
      id: 'gpt-5',
      name: 'GPT-5',
      version: '',
      family: 'OpenAI',
      status: 'stable',
      releaseDate: '2026-04-12',
      contextK: 400,
      params: 'undisclosed',
      modality: ['text', 'vision', 'audio', 'tool'],
      summary: 'OpenAI\u2019s flagship. Heavy reasoning under the hood with adaptive depth — the same model thinks longer when problems are harder.',
      scores: { reason: 91, context: 22, speed: 70, cost: 52, tools: 90, multimodal: 88, code: 86, instruct: 92 },
      benchmarks: { mmlu: 88.1, gpqa: 87.6, swe: 74.2, tau: 80.5, math: 94.2, humaneval: 91.0 },
      costPerM: 10.0,
      tps: 88,
      delta30d: +1.8,
    },
    {
      id: 'claude-opus-4-5',
      name: 'Claude Opus',
      version: '4.5',
      family: 'Anthropic',
      status: 'stable',
      releaseDate: '2026-03-28',
      contextK: 500,
      params: 'undisclosed',
      modality: ['text', 'vision', 'tool'],
      summary: 'Anthropic\u2019s top-tier model. Leads on software engineering and tool-use chains; constitutional training emphasizes calibrated refusal.',
      scores: { reason: 89, context: 30, speed: 64, cost: 48, tools: 94, multimodal: 80, code: 94, instruct: 95 },
      benchmarks: { mmlu: 87.0, gpqa: 83.4, swe: 80.2, tau: 84.0, math: 88.7, humaneval: 93.5 },
      costPerM: 15.0,
      tps: 72,
      delta30d: +2.4,
    },
    {
      id: 'gemini-2-5-pro',
      name: 'Gemini',
      version: '2.5 Pro',
      family: 'Google DeepMind',
      status: 'stable',
      releaseDate: '2026-03-14',
      contextK: 2000,
      params: 'undisclosed',
      modality: ['text', 'vision', 'audio', 'tool'],
      summary: 'Massive native context, deeply multimodal. Pre-eminent on long-document retrieval and video understanding.',
      scores: { reason: 86, context: 100, speed: 76, cost: 62, tools: 84, multimodal: 95, code: 79, instruct: 86 },
      benchmarks: { mmlu: 85.9, gpqa: 84.8, swe: 63.4, tau: 76.8, math: 89.4, humaneval: 84.2 },
      costPerM: 7.0,
      tps: 102,
      delta30d: +1.2,
    },
    {
      id: 'grok-4',
      name: 'Grok',
      version: '4',
      family: 'xAI',
      status: 'stable',
      releaseDate: '2026-04-22',
      contextK: 256,
      params: 'undisclosed',
      modality: ['text', 'vision', 'tool'],
      summary: 'xAI\u2019s frontier model with web-native reasoning. Top scores on hard science benchmarks and adversarial math.',
      scores: { reason: 90, context: 28, speed: 78, cost: 58, tools: 80, multimodal: 76, code: 80, instruct: 82 },
      benchmarks: { mmlu: 85.4, gpqa: 87.9, swe: 72.0, tau: 70.5, math: 92.8, humaneval: 82.4 },
      costPerM: 8.0,
      tps: 110,
      delta30d: +3.6,
    },
    {
      id: 'deepseek-v3-1',
      name: 'DeepSeek',
      version: 'V3.1',
      family: 'DeepSeek',
      status: 'stable',
      releaseDate: '2026-02-08',
      contextK: 128,
      params: '671B (37B active, MoE)',
      modality: ['text', 'tool'],
      summary: 'Open-weights MoE with aggressive cost engineering. Strong reasoner per dollar; community-favored for agentic pipelines.',
      scores: { reason: 84, context: 14, speed: 80, cost: 96, tools: 76, multimodal: 22, code: 84, instruct: 80 },
      benchmarks: { mmlu: 82.5, gpqa: 74.1, swe: 66.8, tau: 65.2, math: 90.0, humaneval: 87.5 },
      costPerM: 0.55,
      tps: 142,
      delta30d: +2.1,
    },
    {
      id: 'qwen-3-max',
      name: 'Qwen3',
      version: 'Max',
      family: 'Alibaba',
      status: 'stable',
      releaseDate: '2026-04-04',
      contextK: 256,
      params: '~ 480B (MoE)',
      modality: ['text', 'vision', 'tool'],
      summary: 'Alibaba\u2019s production frontier. Multilingual leader, strong vision, dense agentic tool-calling.',
      scores: { reason: 82, context: 28, speed: 82, cost: 80, tools: 86, multimodal: 88, code: 82, instruct: 84 },
      benchmarks: { mmlu: 84.0, gpqa: 78.2, swe: 64.7, tau: 73.5, math: 88.3, humaneval: 84.0 },
      costPerM: 2.4,
      tps: 124,
      delta30d: +1.5,
    },
    {
      id: 'glm-4-6',
      name: 'GLM',
      version: '4.6',
      family: 'Zhipu AI',
      status: 'stable',
      releaseDate: '2026-03-20',
      contextK: 200,
      params: '~ 355B (MoE)',
      modality: ['text', 'vision', 'tool'],
      summary: 'Zhipu\u2019s frontier reasoning model. Punching above its weight on code and Chinese-language tasks.',
      scores: { reason: 78, context: 22, speed: 78, cost: 84, tools: 74, multimodal: 64, code: 81, instruct: 78 },
      benchmarks: { mmlu: 80.4, gpqa: 73.0, swe: 64.2, tau: 67.0, math: 84.5, humaneval: 82.0 },
      costPerM: 1.8,
      tps: 130,
      delta30d: +1.0,
    },
    {
      id: 'llama-4-maverick',
      name: 'Llama 4',
      version: 'Maverick',
      family: 'Meta',
      status: 'stable',
      releaseDate: '2026-04-01',
      contextK: 1000,
      params: '402B (17B active, MoE)',
      modality: ['text', 'vision', 'tool'],
      summary: 'Meta\u2019s flagship open-weights MoE. Million-token context, deeply distributed inference.',
      scores: { reason: 76, context: 70, speed: 85, cost: 88, tools: 70, multimodal: 78, code: 74, instruct: 76 },
      benchmarks: { mmlu: 78.4, gpqa: 70.5, swe: 55.2, tau: 60.0, math: 78.5, humaneval: 77.5 },
      costPerM: 0.65,
      tps: 168,
      delta30d: +0.6,
    },
    {
      id: 'mistral-large-2',
      name: 'Mistral',
      version: 'Large 2',
      family: 'Mistral',
      status: 'stable',
      releaseDate: '2026-01-30',
      contextK: 128,
      params: '~ 123B (dense)',
      modality: ['text', 'tool'],
      summary: 'European frontier model. Compact, predictable, strong on French/German; production-friendly licensing.',
      scores: { reason: 71, context: 14, speed: 86, cost: 72, tools: 78, multimodal: 38, code: 70, instruct: 80 },
      benchmarks: { mmlu: 74.3, gpqa: 64.2, swe: 47.1, tau: 62.5, math: 71.0, humaneval: 80.0 },
      costPerM: 3.0,
      tps: 152,
      delta30d: +0.4,
    },
    {
      id: 'kimi-k2',
      name: 'Kimi',
      version: 'K2',
      family: 'Moonshot AI',
      status: 'experimental',
      releaseDate: '2026-05-02',
      contextK: 200,
      params: '~ 1T (MoE, 32B active)',
      modality: ['text', 'tool'],
      summary: 'Moonshot\u2019s open-weights agentic model — built around long-horizon tool sequences. Volatile but climbing.',
      scores: { reason: 80, context: 22, speed: 64, cost: 88, tools: 90, multimodal: 28, code: 86, instruct: 78 },
      benchmarks: { mmlu: 82.0, gpqa: 75.0, swe: 65.5, tau: 78.4, math: 86.2, humaneval: 88.5 },
      costPerM: 1.2,
      tps: 58,
      delta30d: +4.8,
    },
  ],

  releases: [
    { code: 'GPT-5',         headline: 'ADAPTIVE REASONING ROUTER LIVE',          t: 'NOW',  family: 'OpenAI' },
    { code: 'Claude Opus 4.5', headline: 'SWE-BENCH VERIFIED · NEW HIGH 80.2',    t: 'T\u22124M', family: 'Anthropic' },
    { code: 'Gemini 2.5 Pro',headline: '2M TOKEN CONTEXT GENERALLY AVAILABLE',    t: 'T\u221218M',family: 'Google DeepMind' },
    { code: 'Grok 4',        headline: 'HUMANITY\u2019S LAST EXAM · UPDATED',     t: 'T\u22122H', family: 'xAI' },
    { code: 'Kimi K2',       headline: 'AGENTIC HARNESS PUBLISHED · OSS',          t: 'T\u22125H', family: 'Moonshot AI' },
    { code: 'DeepSeek V3.1', headline: 'CHECKPOINT EXPORT \u00B7 HF MIRROR',       t: 'T\u22127H', family: 'DeepSeek' },
    { code: 'Llama 4 Maverick', headline: 'LATENCY DROP \u00B7 18% ON H200',       t: 'T\u221211H',family: 'Meta' },
    { code: 'Qwen3 Max',     headline: 'VISION TOWER UPGRADED \u00B7 + 4.2 GPQA',  t: 'T\u221216H',family: 'Alibaba' },
  ],

  /* Benchmark suites — pick any subset for the matrix radar */
  axes: [
    { id: 'reason',     label: 'REASON',     desc: 'GPQA · ARC-AGI · MUSR composite' },
    { id: 'code',       label: 'CODE',       desc: 'SWE-Bench + HumanEval+ blend' },
    { id: 'context',    label: 'CTX',        desc: 'Effective context, length-needle' },
    { id: 'speed',      label: 'SPEED',      desc: 'p50 tokens/sec, single stream' },
    { id: 'cost',       label: 'COST',       desc: 'Inverse $/1M (higher = cheaper)' },
    { id: 'tools',      label: 'TOOLS',      desc: 'TAU-Bench, Berkeley fn-calling' },
    { id: 'multimodal', label: 'M·MODAL',    desc: 'MMMU, VideoMME, audio bench' },
    { id: 'instruct',   label: 'INSTRUCT',   desc: 'IFEval, MT-Bench, ChatArena' },
  ],

  benchSuites: [
    { id: 'mmlu',       name: 'MMLU-PRO',    desc: 'Multitask language understanding · professional', n: 12032 },
    { id: 'gpqa',       name: 'GPQA',        desc: 'Graduate-level science · Google-proof',          n:   448 },
    { id: 'swe',        name: 'SWE-BENCH',   desc: 'Real software-engineering issues',               n:  2294 },
    { id: 'tau',        name: 'TAU-BENCH',   desc: 'Tool-use in agentic workflows',                  n:   825 },
    { id: 'math',       name: 'MATH-500',    desc: 'Competition mathematics, step-graded',           n:   500 },
    { id: 'humaneval',  name: 'HUMANEVAL+',  desc: 'Code synthesis with augmented tests',             n:   164 },
  ],
};
