/**
 * Ashfall — synthesised audio.  ARCHITECTURE.md §3.12
 *
 * Every sound in this game is generated by the WebAudio graph at runtime. There is not one
 * byte of sample data on disk: gunshots, impacts, footsteps, mechanical clicks, the wind bed
 * and both reverb impulse responses are all built from oscillators, noise buffers and
 * biquads. That constraint is the whole point — it also means the mix has to be authored in
 * physics rather than in a DAW, so this file is organised the way a game mixer is:
 *
 *   sources ─┬─ spatial channel (air LP ▸ propagation delay ▸ HRTF panner)
 *            └─ self channel  (no delay, tiny stereo spread — the player's own gun)
 *                     │
 *                     ├─ dry ───────────────────────────────┐
 *                     ├─ send: far  ▸ convolver (yard IR) ──┤
 *                     └─ send: close ▸ convolver (room IR) ─┤
 *                                                           ▼
 *   ambience ────────────────────────────────────────────▸ duckGain ▸ duckLP
 *                                                           ▼
 *                                      busCompressor ▸ softClip ▸ limiter ▸ masterGain ▸ out
 *
 * `duckGain` + `duckLP` are the concussion model: an explosion slams them shut and they
 * recover over ~2.5 s while a tinnitus tone — deliberately wired *past* the ducker so it
 * survives it — rings down over six seconds.
 *
 * Design rules honoured here:
 *  - `update()` allocates nothing. All vectors are module-scope scratch.
 *  - Voices are pooled: the panner/delay/filter chains are built once and recycled, so a
 *    firefight does not churn the graph. Only the short-lived source+envelope nodes are new
 *    per shot, which WebAudio gives us no way to avoid.
 *  - Nothing throws. If `AudioContext` is missing, unavailable or blocked, every entry point
 *    becomes a no-op and the game runs silent rather than dying.
 */

import * as THREE from '../../vendor/three.module.js';
import { SURFACES, ATMOSPHERE } from '../world/art.js';

/* ========================================================================== */
/* Module-scope scratch — never allocate in update()                          */
/* ========================================================================== */

const _earPos = new THREE.Vector3();
const _earUp = new THREE.Vector3();
const _earFwd = new THREE.Vector3();
const _rayUp = new THREE.Vector3(0, 1, 0);
const _rayOrigin = new THREE.Vector3();
const _srcPos = new THREE.Vector3();
const _tmpVec = new THREE.Vector3();
const _battlePos = new THREE.Vector3();

const SPEED_OF_SOUND = 343.0; // m/s — drives the propagation delay
const MAX_VOICES = 72;
const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
const rnd = Math.random;
/** Symmetric jitter helper: `jit(0.03)` → 0.97 .. 1.03. */
const jit = (amount) => 1 + (rnd() * 2 - 1) * amount;

/* ========================================================================== */
/* Weapon voicing tables                                                      */
/* ========================================================================== */

/**
 * Three genuinely different guns. What distinguishes a 5.56 carbine from a .45 SMG from a
 * 7.62 marksman rifle by ear is (a) where the resonant body sits, (b) how fast it decays and
 * (c) how far the low thump sweeps. Those are the three axes below; the numbers are pulled
 * apart hard enough that the weapons are identifiable blind.
 */
const GUNS = {
  // MK18 carbine — sharp crack, mid-forward body, tight decay.
  rifle: {
    level: 1.0,
    crack: { f: 4200, q: 1.1, g: 0.62, dur: 0.0075 },
    body: [
      { t: 0.0000, type: 'lowpass', f: 900, f2: 420, q: 6.0, g: 0.95, atk: 0.0012, dec: 0.105 },
      { t: 0.0016, type: 'bandpass', f: 1950, f2: 1150, q: 2.6, g: 0.50, atk: 0.0008, dec: 0.062 },
      { t: 0.0035, type: 'lowpass', f: 420, f2: 190, q: 2.2, g: 0.70, atk: 0.0020, dec: 0.200 },
    ],
    thump: { f0: 132, f1: 56, dur: 0.150, g: 0.85, wave: 'triangle' },
    mech: { t: 0.030, g: 0.20, f: 2500 },
    tail: { f: 620, q: 0.9, g: 0.55, dec: 0.34 },
    hp: 60,
  },
  // VECTOR .45 — blunter and darker, very fast decay, audible mechanical clatter.
  smg: {
    level: 0.82,
    crack: { f: 2700, q: 1.4, g: 0.44, dur: 0.0060 },
    body: [
      { t: 0.0000, type: 'lowpass', f: 620, f2: 300, q: 5.0, g: 0.90, atk: 0.0010, dec: 0.070 },
      { t: 0.0012, type: 'bandpass', f: 1320, f2: 820, q: 3.2, g: 0.40, atk: 0.0007, dec: 0.040 },
      { t: 0.0028, type: 'lowpass', f: 330, f2: 165, q: 1.8, g: 0.55, atk: 0.0018, dec: 0.125 },
    ],
    thump: { f0: 108, f1: 46, dur: 0.105, g: 0.62, wave: 'sine' },
    mech: { t: 0.020, g: 0.34, f: 3200 },
    tail: { f: 480, q: 0.9, g: 0.34, dec: 0.24 },
    hp: 70,
  },
  // DMR14 7.62 — enormous, slow, long tail. The one that echoes off the far wall.
  dmr: {
    level: 1.25,
    crack: { f: 5400, q: 0.9, g: 0.78, dur: 0.0090 },
    body: [
      { t: 0.0000, type: 'lowpass', f: 700, f2: 260, q: 7.5, g: 1.05, atk: 0.0014, dec: 0.165 },
      { t: 0.0020, type: 'bandpass', f: 1550, f2: 780, q: 2.2, g: 0.58, atk: 0.0009, dec: 0.095 },
      { t: 0.0042, type: 'lowpass', f: 300, f2: 120, q: 2.6, g: 0.85, atk: 0.0025, dec: 0.340 },
    ],
    thump: { f0: 160, f1: 40, dur: 0.240, g: 1.05, wave: 'triangle' },
    mech: { t: 0.052, g: 0.24, f: 2100 },
    tail: { f: 380, q: 0.8, g: 0.95, dec: 0.55 },
    hp: 45,
  },
};

/** weapon.id / weapon.audio.fire → voicing key. */
const GUN_ALIAS = {
  mk18: 'rifle',
  rifle: 'rifle',
  carbine: 'rifle',
  vector: 'smg',
  smg: 'smg',
  dmr14: 'dmr',
  dmr: 'dmr',
  marksman: 'dmr',
  rifleman: 'rifle',
  support: 'rifle',
  scout: 'smg',
  sniper: 'dmr',
};

/**
 * Footstep voicing. `hardness` from art.js SURFACES scales brightness and level so the table
 * and the gameplay surface response never drift apart.
 */
const FOOT = {
  concrete: { thud: 210, thudDec: 0.055, slap: 2400, slapQ: 1.0, slapDec: 0.038, g: 0.60, grain: 0, ring: 0 },
  metal: { thud: 260, thudDec: 0.045, slap: 3400, slapQ: 1.6, slapDec: 0.030, g: 0.62, grain: 0, ring: 900 },
  wood: { thud: 165, thudDec: 0.085, slap: 1500, slapQ: 3.0, slapDec: 0.050, g: 0.55, grain: 0, ring: 240 },
  gravel: { thud: 150, thudDec: 0.045, slap: 3100, slapQ: 0.8, slapDec: 0.055, g: 0.52, grain: 7, ring: 0 },
  dirt: { thud: 120, thudDec: 0.075, slap: 900, slapQ: 0.7, slapDec: 0.050, g: 0.42, grain: 2, ring: 0 },
  glass: { thud: 190, thudDec: 0.040, slap: 4600, slapQ: 1.2, slapDec: 0.060, g: 0.48, grain: 5, ring: 3200 },
  sandbag: { thud: 105, thudDec: 0.090, slap: 700, slapQ: 0.6, slapDec: 0.045, g: 0.38, grain: 0, ring: 0 },
};

/* ========================================================================== */
/* Factory                                                                    */
/* ========================================================================== */

export function createAudio(game) {
  /* ---------------------------------------------------------------------- */
  /* Inert fallback — returned whenever WebAudio cannot be brought up.       */
  /* ---------------------------------------------------------------------- */

  const NOOP = () => {};
  const inert = {
    ctx: null,
    available: false,
    muted: true,
    volume: 0,
    resume: NOOP,
    update: NOOP,
    setVolume: NOOP,
    setMuted: NOOP,
    setQuality: NOOP,
    playOneShot: NOOP,
    dispose: NOOP,
  };

  const Ctor = typeof window !== 'undefined' ? window.AudioContext || window.webkitAudioContext : null;
  if (!Ctor) return inert;

  let ctx = null;
  try {
    ctx = new Ctor({ latencyHint: 'interactive' });
  } catch {
    return inert;
  }
  if (!ctx || typeof ctx.createGain !== 'function') return inert;

  const rate = ctx.sampleRate || 48000;
  let quality = game?.quality || 'high';
  let disposed = false;
  let liveVoices = 0;

  /* ---------------------------------------------------------------------- */
  /* Noise banks                                                            */
  /* ---------------------------------------------------------------------- */

  /** Reused for every noise layer in the game — a per-shot buffer would be criminal. */
  function makeNoise(seconds, kind) {
    const len = Math.max(1, Math.floor(seconds * rate));
    const buf = ctx.createBuffer(1, len, rate);
    const d = buf.getChannelData(0);
    if (kind === 'pink') {
      // Voss-McCartney-ish: three cascaded one-poles summed. Cheap and close enough.
      let b0 = 0;
      let b1 = 0;
      let b2 = 0;
      for (let i = 0; i < len; i++) {
        const w = rnd() * 2 - 1;
        b0 = 0.99765 * b0 + w * 0.0990460;
        b1 = 0.96300 * b1 + w * 0.2965164;
        b2 = 0.57000 * b2 + w * 1.0526913;
        d[i] = (b0 + b1 + b2 + w * 0.1848) * 0.22;
      }
    } else if (kind === 'bright') {
      // Differentiated white: +6 dB/oct, gives glass and spark layers their fizz.
      let prev = 0;
      for (let i = 0; i < len; i++) {
        const w = rnd() * 2 - 1;
        d[i] = (w - prev) * 0.5;
        prev = w;
      }
    } else if (kind === 'grain') {
      // Sparse decaying impulses — gravel crunch, debris rain, glass shards.
      d.fill(0);
      let i = 0;
      while (i < len) {
        const amp = (rnd() * 2 - 1) * (0.4 + rnd() * 0.6);
        const tail = 4 + ((rnd() * 40) | 0);
        for (let k = 0; k < tail && i + k < len; k++) d[i + k] += amp * Math.exp(-k * 0.35);
        i += 20 + ((rnd() * 260) | 0);
      }
    } else {
      for (let i = 0; i < len; i++) d[i] = rnd() * 2 - 1;
    }
    return buf;
  }

  const bufWhite = makeNoise(2.0, 'white');
  const bufPink = makeNoise(2.4, 'pink');
  const bufBright = makeNoise(1.2, 'bright');
  const bufGrain = makeNoise(1.4, 'grain');

  /** 4 ms exponentially decaying impulse — the transient click at the front of everything. */
  const bufClick = (() => {
    const len = Math.max(8, Math.floor(0.004 * rate));
    const buf = ctx.createBuffer(1, len, rate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < len; i++) {
      const t = i / len;
      d[i] = (rnd() * 2 - 1) * Math.exp(-t * 22) * (1 - t * 0.2);
    }
    // Dirac-like leading edge so the very first sample is the loudest thing in the sound.
    d[0] = 1.0;
    d[1] = -0.72;
    return buf;
  })();

  /* ---------------------------------------------------------------------- */
  /* Impulse responses — generated, never loaded                            */
  /* ---------------------------------------------------------------------- */

  /**
   * Build a reverb IR.
   *
   * The diffuse field is exponentially decaying noise, but raw noise sounds like a hiss
   * gate. Two things fix it: a progressive one-pole lowpass so the high end dies before the
   * low end (air absorption plus wall losses), and a build-up ramp so the tail arrives after
   * the direct sound instead of on top of it.
   *
   * The early-reflection pattern is what actually tells you where you are. For the yard it
   * is sparse and spread over 80 ms — a big space bounded by hard flat things a long way
   * apart. For the interior it is dense and inside 30 ms.
   */
  function makeIR(seconds, decayK, ers, damp0, damp1, buildMs, preMs) {
    const len = Math.max(64, Math.floor(seconds * rate));
    const buf = ctx.createBuffer(2, len, rate);
    const build = Math.max(1, (buildMs / 1000) * rate);
    const pre = Math.max(0, Math.floor((preMs / 1000) * rate));

    for (let c = 0; c < 2; c++) {
      const d = buf.getChannelData(c);
      let z = 0;
      for (let i = 0; i < len; i++) {
        if (i < pre) {
          d[i] = 0;
          continue;
        }
        const t = (i - pre) / rate;
        const env = Math.exp(-decayK * t);
        // Damping coefficient falls with time: the tail gets progressively darker.
        const coef = damp0 + (damp1 - damp0) * Math.min(1, t / seconds);
        z += ((rnd() * 2 - 1) - z) * coef;
        const ramp = Math.min(1, (i - pre) / build);
        d[i] = z * env * ramp;
      }

      // Splat the early reflections. Each is a 1.2 ms filtered micro-burst rather than a
      // single sample; a bare delta reads as a metallic tick and gives the whole IR a comb.
      const w = c === 0 ? 1 : -1;
      for (let e = 0; e < ers.length; e++) {
        const er = ers[e];
        const idx = pre + Math.floor((er[0] / 1000) * rate);
        const wide = 1 + w * er[2] * 0.55;
        const n = Math.max(4, Math.floor(0.0012 * rate));
        let zz = 0;
        for (let k = 0; k < n && idx + k < len; k++) {
          zz += ((rnd() * 2 - 1) - zz) * 0.55;
          d[idx + k] += zz * er[1] * wide * Math.exp(-k / (n * 0.4));
        }
      }
    }

    // Normalise to a predictable peak so the send gains mean the same thing for both IRs.
    let peak = 0;
    for (let c = 0; c < 2; c++) {
      const d = buf.getChannelData(c);
      for (let i = 0; i < d.length; i++) {
        const a = d[i] < 0 ? -d[i] : d[i];
        if (a > peak) peak = a;
      }
    }
    if (peak > 1e-6) {
      const s = 0.86 / peak;
      for (let c = 0; c < 2; c++) {
        const d = buf.getChannelData(c);
        for (let i = 0; i < d.length; i++) d[i] *= s;
      }
    }
    return buf;
  }

  // [time ms, amplitude, stereo bias -1..1]. Yard: far walls, container stacks, the crane.
  const ER_YARD = [
    [9, 0.62, 0.8],
    [14, 0.48, -0.6],
    [21, 0.55, 0.35],
    [27, 0.36, -0.9],
    [34, 0.42, 0.62],
    [41, 0.30, -0.25],
    [47, 0.34, 0.9],
    [55, 0.24, -0.7],
    [63, 0.26, 0.15],
    [71, 0.19, -0.45],
    [79, 0.21, 0.55],
  ];
  // Interior: small hard room, reflections pile up inside 30 ms.
  const ER_CLOSE = [
    [3, 0.75, 0.6],
    [5, 0.62, -0.8],
    [8, 0.58, 0.3],
    [11, 0.50, -0.4],
    [14, 0.44, 0.85],
    [18, 0.38, -0.55],
    [23, 0.30, 0.2],
    [29, 0.24, -0.75],
  ];

  const irYard = makeIR(1.45, 3.1, ER_YARD, 0.62, 0.16, 34, 7);
  const irClose = makeIR(0.44, 9.4, ER_CLOSE, 0.80, 0.34, 9, 2);

  /* ---------------------------------------------------------------------- */
  /* Master chain                                                           */
  /* ---------------------------------------------------------------------- */

  const masterGain = ctx.createGain();
  masterGain.gain.value = 0.7;
  masterGain.connect(ctx.destination);

  // Brick-wall-ish safety limiter. Fast attack, short release; it should never be working
  // hard except on explosions.
  const limiter = ctx.createDynamicsCompressor();
  limiter.threshold.value = -1.4;
  limiter.knee.value = 0.0;
  limiter.ratio.value = 20.0;
  limiter.attack.value = 0.001;
  limiter.release.value = 0.055;
  limiter.connect(masterGain);

  // Soft clip after the bus compressor: rounds transients that outrun the limiter's attack,
  // which is exactly what a gunshot does.
  const softClip = ctx.createWaveShaper();
  {
    const n = 2048;
    const curve = new Float32Array(n);
    for (let i = 0; i < n; i++) {
      const x = (i / (n - 1)) * 2 - 1;
      curve[i] = Math.tanh(x * 1.35) / Math.tanh(1.35);
    }
    softClip.curve = curve;
    softClip.oversample = '2x';
  }
  softClip.connect(limiter);

  // Bus compressor: glues the layers of a shot together and stops distant fire disappearing.
  const busComp = ctx.createDynamicsCompressor();
  busComp.threshold.value = -15;
  busComp.knee.value = 11;
  busComp.ratio.value = 3.2;
  busComp.attack.value = 0.004;
  busComp.release.value = 0.19;
  busComp.connect(softClip);

  // Concussion pair. `duckLP` is the muffled-hearing filter; `duckGain` is the level drop.
  const duckLP = ctx.createBiquadFilter();
  duckLP.type = 'lowpass';
  duckLP.frequency.value = 20000;
  duckLP.Q.value = 0.5;
  duckLP.connect(busComp);

  const duckGain = ctx.createGain();
  duckGain.gain.value = 1.0;
  duckGain.connect(duckLP);

  const sfxBus = ctx.createGain();
  sfxBus.gain.value = 1.0;
  sfxBus.connect(duckGain);

  const ambienceBus = ctx.createGain();
  ambienceBus.gain.value = 0.0; // faded in once the context is genuinely running
  ambienceBus.connect(duckGain);

  const uiBus = ctx.createGain();
  uiBus.gain.value = 0.9;
  uiBus.connect(duckGain);

  // Reverb returns.
  const convFar = ctx.createConvolver();
  convFar.normalize = false;
  convFar.buffer = irYard;
  const returnFar = ctx.createGain();
  returnFar.gain.value = 0.9;
  convFar.connect(returnFar);
  returnFar.connect(duckGain);

  const convClose = ctx.createConvolver();
  convClose.normalize = false;
  convClose.buffer = irClose;
  const returnClose = ctx.createGain();
  returnClose.gain.value = 0.12;
  convClose.connect(returnClose);
  returnClose.connect(duckGain);

  // Pre-convolver tilt: reverb should be darker than the dry signal or the space sounds tiled.
  const sendFarIn = ctx.createBiquadFilter();
  sendFarIn.type = 'lowpass';
  sendFarIn.frequency.value = 4200;
  sendFarIn.Q.value = 0.4;
  sendFarIn.connect(convFar);

  const sendCloseIn = ctx.createBiquadFilter();
  sendCloseIn.type = 'lowpass';
  sendCloseIn.frequency.value = 6500;
  sendCloseIn.Q.value = 0.4;
  sendCloseIn.connect(convClose);

  // Tinnitus deliberately bypasses the ducker and the limiter: after a grenade the world
  // goes away and the ring is all that is left.
  const tinnitusBus = ctx.createGain();
  tinnitusBus.gain.value = 0.0;
  tinnitusBus.connect(masterGain);

  /* ---------------------------------------------------------------------- */
  /* Voice channels (pooled)                                                */
  /* ---------------------------------------------------------------------- */

  /**
   * A channel is a reusable spatialisation strip. `input` carries dry + sends; `tailIn`
   * carries send-only material, which is how a gunshot's reverb tail can be much longer and
   * louder than its dry signal without smearing the transient.
   */
  function makeChannel(mode) {
    const input = ctx.createGain();
    input.gain.value = 1;

    const hp = ctx.createBiquadFilter();
    hp.type = 'highpass';
    hp.frequency.value = 24;
    hp.Q.value = 0.7;

    // Air absorption. Cutoff is set per sound from distance.
    const air = ctx.createBiquadFilter();
    air.type = 'lowpass';
    air.frequency.value = 20000;
    air.Q.value = 0.5;

    const dry = ctx.createGain();
    const sFar = ctx.createGain();
    const sClose = ctx.createGain();
    const tailIn = ctx.createGain();
    tailIn.gain.value = 1;

    let spatial = null;
    let delay = null;

    input.connect(hp);
    hp.connect(air);

    if (mode === 'self') {
      // The player's own weapon: no propagation delay, no HRTF (a source at the listener's
      // own head makes HRTF panners fold), just a small stereo spread set per shot.
      spatial = ctx.createStereoPanner ? ctx.createStereoPanner() : ctx.createGain();
      air.connect(spatial);
    } else {
      delay = ctx.createDelay(1.5);
      delay.delayTime.value = 0;
      const p = ctx.createPanner();
      p.panningModel = mode === 'hrtf' ? 'HRTF' : 'equalpower';
      p.distanceModel = 'inverse';
      p.refDistance = 3.5;
      p.maxDistance = 400;
      p.rolloffFactor = 0.85;
      p.coneInnerAngle = 360;
      p.coneOuterAngle = 360;
      p.coneOuterGain = 1;
      spatial = p;
      air.connect(delay);
      delay.connect(p);
    }

    spatial.connect(dry);
    spatial.connect(sFar);
    spatial.connect(sClose);
    tailIn.connect(sFar);
    tailIn.connect(sClose);

    dry.connect(sfxBus);
    sFar.connect(sendFarIn);
    sClose.connect(sendCloseIn);

    return { mode, input, tailIn, air, delay, spatial, dry, sFar, sClose, freeAt: 0, lastUse: 0 };
  }

  const poolHRTF = [];
  const poolFlat = [];
  const poolSelf = [];

  function sizePools() {
    const hrtfN = quality === 'low' ? 0 : quality === 'medium' ? 8 : 14;
    const flatN = quality === 'low' ? 12 : 14;
    const selfN = 6;
    while (poolHRTF.length < hrtfN) poolHRTF.push(makeChannel('hrtf'));
    while (poolFlat.length < flatN) poolFlat.push(makeChannel('flat'));
    while (poolSelf.length < selfN) poolSelf.push(makeChannel('self'));
  }
  sizePools();

  function acquire(pool, t, hold) {
    if (!pool.length) return null;
    let best = null;
    for (let i = 0; i < pool.length; i++) {
      const c = pool[i];
      if (c.freeAt <= t) {
        best = c;
        break;
      }
      if (!best || c.lastUse < best.lastUse) best = c;
    }
    if (!best) best = pool[0];
    best.freeAt = t + hold;
    best.lastUse = t;
    return best;
  }

  /* ---------------------------------------------------------------------- */
  /* Layer primitives                                                       */
  /* ---------------------------------------------------------------------- */

  function budget() {
    return liveVoices < MAX_VOICES;
  }

  function track(node) {
    liveVoices++;
    node.onended = () => {
      liveVoices--;
      try {
        node.disconnect();
      } catch {
        /* already torn down */
      }
    };
  }

  /** Filtered noise burst with an exponential decay and an optional filter sweep. */
  function burst(dest, t, type, f, f2, q, gain, atk, dec, buf, playRate) {
    if (gain <= 0.0005 || !budget()) return;
    const b = buf || bufWhite;
    const src = ctx.createBufferSource();
    src.buffer = b;
    src.playbackRate.value = playRate || 1;

    const flt = ctx.createBiquadFilter();
    flt.type = type;
    flt.Q.value = q;
    flt.frequency.setValueAtTime(Math.max(20, f), t);
    if (f2 && Math.abs(f2 - f) > 1) {
      flt.frequency.exponentialRampToValueAtTime(Math.max(20, f2), t + Math.max(0.004, dec));
    }

    const g = ctx.createGain();
    const a = Math.max(0.0004, atk);
    const d = Math.max(0.006, dec);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(Math.max(0.0002, gain), t + a);
    g.gain.exponentialRampToValueAtTime(0.0001, t + a + d);
    g.gain.setValueAtTime(0, t + a + d + 0.002);

    src.connect(flt);
    flt.connect(g);
    g.connect(dest);

    const span = a + d + 0.02;
    const off = Math.max(0, rnd() * Math.max(0.01, b.duration - span - 0.02));
    track(src);
    try {
      src.start(t, off, span);
    } catch {
      liveVoices--;
    }
  }

  /** Pitched tone with an exponential frequency sweep — the low thump under every shot. */
  function tone(dest, t, wave, f0, f1, dur, gain, atk, shape) {
    if (gain <= 0.0005 || !budget()) return;
    const osc = ctx.createOscillator();
    osc.type = wave || 'sine';
    osc.frequency.setValueAtTime(Math.max(12, f0), t);
    osc.frequency.exponentialRampToValueAtTime(Math.max(12, f1), t + Math.max(0.01, dur));

    const g = ctx.createGain();
    const a = Math.max(0.0008, atk || 0.002);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(gain, t + a);
    g.gain.exponentialRampToValueAtTime(0.0001, t + a + dur);
    g.gain.setValueAtTime(0, t + a + dur + 0.002);

    if (shape) {
      const ws = ctx.createWaveShaper();
      ws.curve = shape;
      osc.connect(ws);
      ws.connect(g);
    } else {
      osc.connect(g);
    }
    g.connect(dest);

    track(osc);
    try {
      osc.start(t);
      osc.stop(t + a + dur + 0.03);
    } catch {
      liveVoices--;
    }
  }

  /** 1-2 ms transient. This is the "crack" — without it a gunshot is a whoomph. */
  function transient(dest, t, f, q, gain, dur) {
    if (gain <= 0.0005 || !budget()) return;
    const src = ctx.createBufferSource();
    src.buffer = bufClick;
    src.playbackRate.value = clamp(0.004 / Math.max(0.0008, dur), 0.35, 4);

    const flt = ctx.createBiquadFilter();
    flt.type = 'bandpass';
    flt.frequency.value = Math.max(120, f);
    flt.Q.value = q;

    const g = ctx.createGain();
    g.gain.setValueAtTime(gain, t);
    g.gain.exponentialRampToValueAtTime(0.0001, t + Math.max(0.002, dur * 2.2));

    src.connect(flt);
    flt.connect(g);
    g.connect(dest);
    track(src);
    try {
      src.start(t);
    } catch {
      liveVoices--;
    }
  }

  /** Inharmonic metallic ring — casings, metal impacts, bolt release. */
  function ring(dest, t, f, dur, gain, count, spread) {
    const partials = count || 3;
    // Inharmonic ratios: a struck metal plate is nothing like a harmonic series.
    const RATIO = [1, 2.756, 5.404, 8.933, 13.34];
    for (let i = 0; i < partials; i++) {
      const r = RATIO[i % RATIO.length] * (1 + (rnd() * 2 - 1) * (spread || 0.04));
      const d = dur * Math.pow(0.62, i);
      tone(dest, t + i * 0.0006, 'sine', f * r, f * r * 0.985, d, gain * Math.pow(0.58, i), 0.0009);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Routing                                                                */
  /* ---------------------------------------------------------------------- */

  let indoor = 0; // 0 outdoors, 1 fully enclosed
  let ducking = 0; // 0 clear, 1 fully concussed

  /**
   * Configure a channel for a sound at `pos`, `hold` seconds long, and return it.
   * Sets the air-absorption cutoff, the propagation delay and both reverb sends.
   */
  function routeAt(pos, t, hold, opts) {
    const spatialise = !!pos;
    let dist = 0;
    if (spatialise) {
      _srcPos.copy(pos);
      dist = _srcPos.distanceTo(_earPos);
    }

    const near = dist < 26;
    const pool = spatialise ? (near && poolHRTF.length ? poolHRTF : poolFlat) : poolSelf;
    const ch = acquire(pool, t, hold);
    if (!ch) return null;

    if (spatialise) {
      const p = ch.spatial;
      if (p.positionX) {
        p.positionX.setValueAtTime(_srcPos.x, t);
        p.positionY.setValueAtTime(_srcPos.y, t);
        p.positionZ.setValueAtTime(_srcPos.z, t);
      } else if (p.setPosition) {
        p.setPosition(_srcPos.x, _srcPos.y, _srcPos.z);
      }
      // Air absorption: roughly -3 dB/octave per 40 m, floored so far shots keep a body.
      const cut = clamp(19000 * Math.exp(-dist / 46) + 420, 380, 20000);
      ch.air.frequency.setValueAtTime(cut, t);
      if (ch.delay) ch.delay.delayTime.setValueAtTime(clamp(dist / SPEED_OF_SOUND, 0, 1.4), t);
    } else {
      const p = ch.spatial;
      if (p.pan) p.pan.setValueAtTime(clamp((opts && opts.pan) || (rnd() * 2 - 1) * 0.09, -1, 1), t);
      ch.air.frequency.setValueAtTime((opts && opts.cut) || 20000, t);
    }

    // Reverb sends. Openness (1 - indoor) drives the big yard IR; enclosure drives the short
    // one. Distant sources send more, because that is what "far away in a big space" means.
    const distFactor = spatialise ? clamp(0.35 + dist / 55, 0.35, 1.7) : 0.42;
    const wetScale = (opts && opts.wet !== undefined ? opts.wet : 1) * distFactor;
    ch.sFar.gain.setValueAtTime(clamp(0.32 * wetScale * (1 - indoor * 0.68), 0, 2.2), t);
    ch.sClose.gain.setValueAtTime(clamp(0.10 * wetScale * (0.14 + indoor * 1.55), 0, 2.2), t);
    ch.dry.gain.setValueAtTime(1, t);
    ch.tailIn.gain.setValueAtTime((opts && opts.tailGain) || 1, t);
    return ch;
  }

  /* ---------------------------------------------------------------------- */
  /* Gunshots                                                               */
  /* ---------------------------------------------------------------------- */

  function playGun(key, t, pos, volume, isSelf) {
    const P = GUNS[key] || GUNS.rifle;
    const lean = quality === 'low';
    const dist = pos ? pos.distanceTo(_earPos) : 0;

    const ch = routeAt(isSelf ? null : pos, t, 1.4, {
      wet: 1.15,
      tailGain: 1.0,
      pan: isSelf ? (rnd() * 2 - 1) * 0.07 : 0,
    });
    if (!ch) return;

    // Micro-randomisation. ±3% on pitch and level: enough that sustained fire breathes,
    // little enough that the weapon still sounds like itself round after round.
    const jp = jit(0.03);
    const jl = jit(0.03) * (volume === undefined ? 1 : volume) * P.level;
    const dest = ch.input;

    // 1. Transient crack. Attenuates fastest with distance — a shot 80 m away is all body.
    const crackScale = pos ? clamp(1 - dist / 70, 0.12, 1) : 1;
    transient(dest, t, P.crack.f * jp, P.crack.q, P.crack.g * jl * crackScale, P.crack.dur);

    // 2. Body: resonant noise bursts at staggered centres. This is the gun's character.
    for (let i = 0; i < P.body.length; i++) {
      if (lean && i === 1) continue;
      const b = P.body[i];
      burst(
        dest,
        t + b.t,
        b.type,
        b.f * jp,
        b.f2 * jp,
        b.q,
        b.g * jl,
        b.atk,
        b.dec * jit(0.05),
        i === 1 ? bufBright : bufWhite,
        jit(0.06)
      );
    }

    // 3. Low thump — the pressure wave. Sweeps down fast; that sweep is the "weight".
    tone(dest, t, P.thump.wave, P.thump.f0 * jp, P.thump.f1 * jp, P.thump.dur, P.thump.g * jl, 0.0018);

    // 4. Mechanical layer: bolt carrier slamming, quieter and behind the report.
    if (!lean) {
      const mt = t + P.mech.t * jit(0.12);
      burst(dest, mt, 'bandpass', P.mech.f * jp, P.mech.f * 0.55, 3.4, P.mech.g * jl * 0.9, 0.0006, 0.014, bufBright, 1);
      burst(dest, mt + 0.006, 'bandpass', 720, 400, 2.6, P.mech.g * jl * 0.55, 0.0008, 0.032, bufWhite, 1);
    }

    // 5. Tail — send-only, so it feeds the yard convolver without smearing the dry transient.
    if (!lean) {
      const openness = 1 - indoor * 0.5;
      burst(
        ch.tailIn,
        t + 0.004,
        'bandpass',
        P.tail.f * jp,
        P.tail.f * 0.45,
        P.tail.q,
        P.tail.g * jl * openness * 1.5,
        0.0025,
        P.tail.dec,
        bufPink,
        1
      );
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Impacts                                                                */
  /* ---------------------------------------------------------------------- */

  function playImpact(surface, t, pos, volume) {
    const s = SURFACES[surface] || SURFACES.concrete;
    const hard = s.hardness;
    const v = (volume === undefined ? 1 : volume) * jit(0.05);
    const ch = routeAt(pos, t, 0.75, { wet: 0.9 });
    if (!ch) return;
    const d = ch.input;
    const jp = jit(0.06);
    const lean = quality === 'low';

    switch (surface) {
      case 'metal': {
        // Ping: a bright strike plus a pitched inharmonic ring that hangs on.
        transient(d, t, 5200 * jp, 1.2, 0.42 * v, 0.0025);
        burst(d, t, 'bandpass', 2600 * jp, 1500 * jp, 2.4, 0.34 * v, 0.0006, 0.030, bufBright, 1);
        if (!lean) ring(d, t + 0.001, (1550 + rnd() * 900) * jp, 0.30, 0.20 * v, 3, 0.05);
        burst(d, t, 'lowpass', 380, 190, 2.0, 0.20 * v, 0.0016, 0.050, bufWhite, 1);
        break;
      }
      case 'wood': {
        // Crack then splinter. Short, dry, mid-heavy.
        transient(d, t, 2400 * jp, 1.6, 0.34 * v, 0.0022);
        burst(d, t, 'bandpass', 1250 * jp, 640 * jp, 5.5, 0.42 * v, 0.0008, 0.042, bufWhite, jit(0.08));
        burst(d, t + 0.004, 'lowpass', 330, 170, 2.2, 0.30 * v, 0.0016, 0.075, bufWhite, 1);
        if (!lean) burst(d, t + 0.010, 'highpass', 3200, 2200, 0.8, 0.13 * v, 0.002, 0.090, bufGrain, 1.4);
        break;
      }
      case 'dirt': {
        transient(d, t, 900 * jp, 0.9, 0.13 * v, 0.003);
        burst(d, t, 'lowpass', 320 * jp, 130, 1.4, 0.46 * v, 0.0022, 0.085, bufWhite, jit(0.1));
        tone(d, t, 'sine', 92 * jp, 52, 0.075, 0.24 * v, 0.003);
        break;
      }
      case 'gravel': {
        transient(d, t, 3400 * jp, 0.9, 0.20 * v, 0.0022);
        burst(d, t, 'lowpass', 520 * jp, 220, 1.6, 0.34 * v, 0.0018, 0.055, bufWhite, 1);
        // Scattered stone chatter.
        if (!lean) burst(d, t + 0.006, 'bandpass', 2900, 1500, 1.1, 0.22 * v, 0.002, 0.150, bufGrain, jit(0.2));
        break;
      }
      case 'glass': {
        transient(d, t, 7200 * jp, 1.0, 0.40 * v, 0.0018);
        burst(d, t, 'highpass', 3600, 2600, 0.7, 0.34 * v, 0.001, 0.055, bufBright, 1);
        // Shards: a handful of short high pings at unrelated pitches.
        if (!lean) {
          const n = 5 + ((rnd() * 5) | 0);
          for (let i = 0; i < n; i++) {
            const ft = t + 0.008 + rnd() * 0.22;
            tone(d, ft, 'sine', (2600 + rnd() * 4200) * jp, (2000 + rnd() * 2600), 0.05 + rnd() * 0.09, 0.075 * v, 0.001);
          }
          burst(d, t + 0.02, 'highpass', 2600, 2000, 0.8, 0.16 * v, 0.004, 0.40, bufGrain, 1.6);
        }
        break;
      }
      case 'sandbag': {
        // No transient worth speaking of — the whole point of a sandbag.
        burst(d, t, 'lowpass', 240 * jp, 105, 1.1, 0.50 * v, 0.003, 0.105, bufPink, jit(0.1));
        tone(d, t, 'sine', 76 * jp, 44, 0.090, 0.20 * v, 0.004);
        if (!lean) burst(d, t + 0.012, 'bandpass', 1400, 900, 1.0, 0.07 * v, 0.004, 0.120, bufWhite, 1);
        break;
      }
      case 'flesh': {
        burst(d, t, 'lowpass', 620 * jp, 240, 2.6, 0.44 * v, 0.0012, 0.048, bufWhite, jit(0.1));
        tone(d, t, 'sine', 128 * jp, 62, 0.055, 0.26 * v, 0.002);
        if (!lean) burst(d, t + 0.006, 'bandpass', 1800, 1100, 1.4, 0.10 * v, 0.002, 0.070, bufWhite, 1);
        break;
      }
      default: {
        // Concrete: hard flat thwack, dust puff behind it.
        transient(d, t, 4400 * jp, 1.1, 0.38 * v * hard, 0.0022);
        burst(d, t, 'bandpass', 950 * jp, 480 * jp, 3.2, 0.50 * v, 0.0009, 0.052, bufWhite, jit(0.08));
        burst(d, t + 0.002, 'lowpass', 300, 130, 2.0, 0.34 * v, 0.0018, 0.088, bufWhite, 1);
        tone(d, t, 'sine', 108 * jp, 58, 0.062, 0.22 * v, 0.0026);
        if (!lean) burst(d, t + 0.020, 'highpass', 2400, 1200, 0.7, 0.10 * v, 0.006, 0.230, bufPink, 1);
        break;
      }
    }

    // A hard surface in a big space kicks a slap back at you; a sandbag does not.
    if (!lean && hard > 0.35) {
      burst(ch.tailIn, t + 0.002, 'bandpass', 900, 420, 0.9, 0.30 * v * hard, 0.003, 0.14, bufPink, 1);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Footsteps, movement, cloth                                             */
  /* ---------------------------------------------------------------------- */

  function playFootstep(surface, t, pos, volume, speed, heavy) {
    const F = FOOT[surface] || FOOT.concrete;
    const v = (volume === undefined ? 0.6 : volume) * F.g * (heavy ? 1.7 : 1) * jit(0.07);
    const jp = jit(0.08);
    const ch = routeAt(pos, t, 0.5, { wet: 0.55 });
    if (!ch) return;
    const d = ch.input;
    const lean = quality === 'low';

    // Heel: low body of the step.
    burst(d, t, 'lowpass', F.thud * jp, F.thud * 0.42, 1.9, 0.55 * v, 0.0016, F.thudDec * (heavy ? 1.6 : 1), bufPink, jit(0.08));
    tone(d, t, 'sine', F.thud * 0.52 * jp, F.thud * 0.28, F.thudDec * 1.3, 0.24 * v, 0.0035);

    // Scuff: the surface texture. Gravel gets granular, metal gets bright and rings.
    if (F.grain > 0 && !lean) {
      for (let i = 0; i < F.grain; i++) {
        const gt = t + rnd() * 0.055;
        burst(d, gt, 'bandpass', (2000 + rnd() * 3200) * jp, 1400, 1.4, 0.11 * v, 0.0008, 0.020 + rnd() * 0.03, bufGrain, 1 + rnd());
      }
    } else {
      burst(d, t + 0.004, F.slap > 2000 ? 'highpass' : 'bandpass', F.slap * jp, F.slap * 0.6, F.slapQ, 0.26 * v, 0.0012, F.slapDec, bufBright, jit(0.1));
    }

    if (F.ring && !lean) ring(d, t + 0.002, F.ring * jp, 0.16, 0.09 * v, 2, 0.06);

    // Kit rustle — the difference between a footstep and a soldier taking a step.
    if (!lean) playCloth(d, t + 0.012, 0.26 * v * (0.6 + clamp((speed || 3) / 6, 0, 1)));
  }

  /** Nylon and webbing. Band-limited noise with a slow attack; never a click. */
  function playCloth(dest, t, amount) {
    if (amount <= 0.004) return;
    burst(dest, t, 'bandpass', (1500 + rnd() * 1100) * jit(0.1), 700, 1.1, 0.30 * amount, 0.010, 0.075, bufPink, jit(0.15));
    burst(dest, t + 0.020, 'highpass', 3400, 2400, 0.8, 0.13 * amount, 0.012, 0.060, bufBright, 1);
  }

  /** 2D cloth for viewmodel actions (ADS, raise, inspect). */
  function selfCloth(t, amount) {
    const ch = routeAt(null, t, 0.3, { wet: 0.3 });
    if (ch) playCloth(ch.input, t, amount);
  }

  /* ---------------------------------------------------------------------- */
  /* Mechanical (magazine, bolt, trigger)                                   */
  /* ---------------------------------------------------------------------- */

  function playMech(kind, t, weaponId) {
    // Heavier gun, lower-pitched hardware.
    const key = GUN_ALIAS[weaponId] || 'rifle';
    const mass = key === 'dmr' ? 0.82 : key === 'smg' ? 1.18 : 1.0;
    const ch = routeAt(null, t, 0.6, { wet: 0.42 });
    if (!ch) return;
    const d = ch.input;
    const jp = jit(0.04) * mass;

    switch (kind) {
      case 'magout':
        // Catch releases, magazine drags out of the well, plastic on aluminium.
        transient(d, t, 3000 * jp, 2.0, 0.24, 0.0022);
        burst(d, t + 0.004, 'bandpass', 1500 * jp, 900, 3.0, 0.20, 0.001, 0.030, bufWhite, 1);
        burst(d, t + 0.030, 'bandpass', 620 * jp, 380, 2.2, 0.17, 0.004, 0.075, bufPink, 1);
        playCloth(d, t + 0.02, 0.28);
        break;
      case 'magin':
        // Two-stage: the mag entering the well, then a solid seat.
        burst(d, t, 'bandpass', 900 * jp, 620, 1.8, 0.14, 0.004, 0.045, bufPink, 1);
        transient(d, t + 0.052, 2200 * jp, 1.6, 0.34, 0.0026);
        burst(d, t + 0.052, 'lowpass', 520 * jp, 240, 2.6, 0.32, 0.0012, 0.060, bufWhite, 1);
        tone(d, t + 0.052, 'sine', 150 * jp, 84, 0.055, 0.16, 0.002);
        break;
      case 'boltback':
        // Charging handle drawn: a scrape then the sear catching.
        burst(d, t, 'bandpass', 2100 * jp, 1400, 1.6, 0.16, 0.006, 0.070, bufBright, 1);
        transient(d, t + 0.070, 3400 * jp, 2.4, 0.22, 0.0018);
        break;
      case 'boltrelease':
        // Bolt slams home. Loud, metallic, with a short ring.
        transient(d, t, 4200 * jp, 1.4, 0.40, 0.0022);
        burst(d, t, 'bandpass', 1900 * jp, 900, 2.8, 0.36, 0.0008, 0.036, bufBright, 1);
        burst(d, t + 0.003, 'lowpass', 480 * jp, 210, 2.4, 0.30, 0.0014, 0.070, bufWhite, 1);
        ring(d, t + 0.002, 2400 * jp, 0.13, 0.11, 3, 0.05);
        break;
      case 'boltlock':
        // Bolt catch engaging on an empty mag — the sound that says "reload".
        transient(d, t, 3600 * jp, 2.2, 0.30, 0.0020);
        burst(d, t, 'bandpass', 2600 * jp, 1500, 3.6, 0.22, 0.0008, 0.028, bufBright, 1);
        ring(d, t, 3100 * jp, 0.10, 0.09, 2, 0.05);
        break;
      case 'dryfire':
        transient(d, t, 3200 * jp, 3.0, 0.22, 0.0016);
        burst(d, t, 'bandpass', 1700 * jp, 1100, 4.0, 0.14, 0.0006, 0.018, bufBright, 1);
        break;
      case 'trigger':
        transient(d, t, 2600 * jp, 4.0, 0.07, 0.0012);
        break;
      case 'weaponraise':
        playCloth(d, t, 0.7);
        burst(d, t + 0.09, 'bandpass', 1200 * jp, 700, 2.2, 0.13, 0.003, 0.045, bufWhite, 1);
        break;
      case 'weaponlower':
        playCloth(d, t, 0.55);
        burst(d, t + 0.06, 'lowpass', 600 * jp, 320, 1.8, 0.10, 0.005, 0.060, bufPink, 1);
        break;
      case 'inspect':
        playCloth(d, t, 0.5);
        burst(d, t + 0.14, 'bandpass', 2400 * jp, 1500, 3.0, 0.09, 0.002, 0.030, bufBright, 1);
        burst(d, t + 0.30, 'bandpass', 1500 * jp, 900, 2.6, 0.07, 0.002, 0.035, bufWhite, 1);
        break;
      case 'adsin':
        playCloth(d, t, 0.34);
        transient(d, t + 0.05, 1800 * jp, 3.0, 0.045, 0.0016);
        break;
      case 'adsout':
        playCloth(d, t, 0.26);
        break;
      default:
        transient(d, t, 2400 * jp, 2.4, 0.12, 0.002);
        break;
    }
  }

  /** Ejected brass hitting concrete: a tick, a pitched ring and a couple of bounces. */
  function playCasing(t, pos, volume, weaponId) {
    const key = GUN_ALIAS[weaponId] || 'rifle';
    const base = (key === 'dmr' ? 2600 : key === 'smg' ? 4200 : 3500) * jit(0.10);
    const v = (volume === undefined ? 0.5 : volume) * jit(0.12);
    const ch = routeAt(pos || null, t, 0.9, { wet: 0.6 });
    if (!ch) return;
    const d = ch.input;
    const bounces = quality === 'low' ? 1 : 2 + ((rnd() * 2) | 0);
    let bt = t;
    let amp = v;
    for (let i = 0; i < bounces; i++) {
      transient(d, bt, base * (1 + i * 0.08), 2.2, 0.10 * amp, 0.0014);
      ring(d, bt, base * (1 - i * 0.03), 0.085 - i * 0.018, 0.10 * amp, i === 0 ? 3 : 2, 0.06);
      bt += 0.055 + rnd() * 0.085;
      amp *= 0.52;
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Combat feedback                                                        */
  /* ---------------------------------------------------------------------- */

  /**
   * Supersonic whizz-by. The trick is the Doppler: a bandpass whose centre sweeps *down*
   * fast, preceded by a tiny crack. That descending sweep is the whole illusion.
   */
  function playWhizz(t, pos, volume) {
    const v = (volume === undefined ? 0.6 : volume) * jit(0.1);
    const ch = routeAt(pos, t, 0.45, { wet: 0.5 });
    if (!ch) return;
    const d = ch.input;
    const f0 = (2600 + rnd() * 1800) * jit(0.05);
    transient(d, t, f0 * 1.7, 1.0, 0.30 * v, 0.0016);
    burst(d, t, 'bandpass', f0, f0 * 0.24, 3.4, 0.52 * v, 0.0018, 0.075, bufBright, jit(0.12));
    burst(d, t + 0.004, 'bandpass', f0 * 0.5, f0 * 0.12, 2.0, 0.26 * v, 0.003, 0.110, bufWhite, 1);
  }

  /** Hit confirmation. Short, dry, 2D, and it must land inside 100 ms of the shot. */
  function playTick(t, kind) {
    const ch = routeAt(null, t, 0.3, { wet: 0.12 });
    if (!ch) return;
    const d = ch.input;
    if (kind === 'head') {
      tone(d, t, 'square', 2450, 2400, 0.030, 0.075, 0.0009);
      tone(d, t + 0.020, 'square', 3300, 3250, 0.038, 0.055, 0.0009);
    } else if (kind === 'kill') {
      tone(d, t, 'triangle', 1500, 1480, 0.045, 0.085, 0.001);
      tone(d, t + 0.045, 'triangle', 1000, 980, 0.100, 0.075, 0.0012);
      burst(d, t, 'bandpass', 2600, 1600, 2.0, 0.06, 0.0008, 0.030, bufBright, 1);
    } else {
      tone(d, t, 'square', 1720, 1700, 0.028, 0.062, 0.0009);
      burst(d, t, 'bandpass', 3400, 2200, 2.4, 0.035, 0.0006, 0.018, bufBright, 1);
    }
  }

  /** Rounds landing on a body — the shooter's confirmation from across the yard. */
  function playFleshHit(t, pos, volume, head) {
    playImpact('flesh', t, pos, (volume === undefined ? 0.7 : volume) * (head ? 1.25 : 1));
    if (head) {
      const ch = routeAt(pos, t, 0.4, { wet: 0.7 });
      if (ch) {
        transient(ch.input, t, 2600, 1.4, 0.22 * (volume || 0.7), 0.002);
        burst(ch.input, t, 'bandpass', 780, 380, 4.0, 0.24 * (volume || 0.7), 0.001, 0.060, bufWhite, 1);
      }
    }
  }

  /** A man going down: a short vocal collapse, then the body and kit hitting the ground. */
  function playDeath(t, pos, volume) {
    const v = (volume === undefined ? 0.8 : volume) * jit(0.06);
    const ch = routeAt(pos, t, 1.6, { wet: 0.9 });
    if (!ch) return;
    const d = ch.input;
    const f = (150 + rnd() * 55) * jit(0.04);
    // Vocal: a formant-ish pair falling in pitch.
    tone(d, t, 'sawtooth', f, f * 0.55, 0.34, 0.055 * v, 0.014);
    burst(d, t, 'bandpass', 620, 380, 5.0, 0.18 * v, 0.012, 0.30, bufPink, 1);
    burst(d, t + 0.02, 'bandpass', 1450, 900, 3.0, 0.09 * v, 0.020, 0.26, bufWhite, 1);
    // Impact with the deck, ~450 ms later: body, then rifle, then kit.
    const bt = t + 0.42 + rnd() * 0.18;
    burst(d, bt, 'lowpass', 230, 95, 1.6, 0.42 * v, 0.003, 0.130, bufPink, 1);
    tone(d, bt, 'sine', 78, 44, 0.110, 0.24 * v, 0.004);
    playCloth(d, bt + 0.02, 0.55 * v);
    if (quality !== 'low') {
      const rt = bt + 0.10 + rnd() * 0.10;
      transient(d, rt, 3200, 1.8, 0.16 * v, 0.002);
      ring(d, rt, 1400, 0.14, 0.09 * v, 3, 0.06);
    }
  }

  /** Player taking rounds: a dull body thump plus a brief high whine. */
  function playHurt(t, amount) {
    const v = clamp(0.35 + (amount || 20) / 70, 0.35, 1.1);
    const ch = routeAt(null, t, 0.7, { wet: 0.25 });
    if (!ch) return;
    const d = ch.input;
    transient(d, t, 900, 1.2, 0.28 * v, 0.003);
    burst(d, t, 'lowpass', 420, 150, 2.4, 0.50 * v, 0.002, 0.11, bufPink, 1);
    tone(d, t, 'sine', 105, 52, 0.13, 0.32 * v, 0.003);
    if (quality !== 'low') tone(d, t + 0.01, 'sine', 3100, 2600, 0.30, 0.020 * v, 0.006);
  }

  /* ---------------------------------------------------------------------- */
  /* Explosions, tinnitus, ducking                                          */
  /* ---------------------------------------------------------------------- */

  let tinnitusOsc = null;
  let tinnitusOsc2 = null;

  function startTinnitus(t, strength) {
    if (quality === 'low') return;
    if (!tinnitusOsc) {
      try {
        tinnitusOsc = ctx.createOscillator();
        tinnitusOsc.type = 'sine';
        tinnitusOsc.frequency.value = 4380;
        tinnitusOsc2 = ctx.createOscillator();
        tinnitusOsc2.type = 'sine';
        tinnitusOsc2.frequency.value = 6620;
        const g2 = ctx.createGain();
        g2.gain.value = 0.35;
        tinnitusOsc.connect(tinnitusBus);
        tinnitusOsc2.connect(g2);
        g2.connect(tinnitusBus);
        tinnitusOsc.start();
        tinnitusOsc2.start();
      } catch {
        tinnitusOsc = null;
        return;
      }
    }
    // Snap up, then a six-second exponential ring-down. Re-triggering re-arms it.
    const g = tinnitusBus.gain;
    const peak = clamp(0.055 * strength, 0.008, 0.075);
    try {
      g.cancelScheduledValues(t);
      g.setValueAtTime(Math.max(0.0001, g.value), t);
      g.linearRampToValueAtTime(peak, t + 0.045);
      g.exponentialRampToValueAtTime(0.0001, t + 6.0);
      g.setValueAtTime(0, t + 6.05);
    } catch {
      /* automation race — harmless */
    }
    // Detune slightly each time so it never sounds like the same test tone.
    if (tinnitusOsc) tinnitusOsc.frequency.setValueAtTime(4200 + rnd() * 500, t);
    if (tinnitusOsc2) tinnitusOsc2.frequency.setValueAtTime(6300 + rnd() * 700, t);
  }

  function playExplosion(t, pos, power, radius) {
    const p = clamp(power === undefined ? 1 : power, 0.15, 3);
    const dist = pos ? pos.distanceTo(_earPos) : 6;
    const prox = clamp(1 - dist / Math.max(8, (radius || 8) * 3.2), 0, 1);
    const ch = routeAt(pos, t, 3.0, { wet: 1.6, tailGain: 1.6 });
    if (!ch) return;
    const d = ch.input;
    const v = p * jit(0.05);

    // Ignition crack.
    transient(d, t, 3200, 0.8, 0.55 * v, 0.004);
    // Blast: broadband noise through a fast-collapsing lowpass. The collapse is the shockwave.
    burst(d, t, 'lowpass', 2600, 170, 1.1, 1.05 * v, 0.0022, 0.55 * p, bufWhite, 1);
    burst(d, t + 0.008, 'bandpass', 620, 180, 1.6, 0.75 * v, 0.004, 0.85 * p, bufPink, 1);
    // Sub: the part you feel.
    tone(d, t, 'sine', 96 * jit(0.05), 26, 0.80 * p, 0.95 * v, 0.005);
    tone(d, t + 0.02, 'triangle', 62, 19, 1.20 * p, 0.42 * v, 0.010);
    // Debris rain and the rumble that follows it.
    if (quality !== 'low') {
      burst(d, t + 0.10, 'highpass', 1800, 900, 0.8, 0.30 * v, 0.020, 1.30, bufGrain, 1.2);
      burst(ch.tailIn, t + 0.01, 'lowpass', 900, 220, 0.8, 1.5 * v, 0.010, 1.60, bufPink, 1);
    }

    // Concussion — only if it was close enough to matter.
    if (prox > 0.02) {
      ducking = clamp(ducking + prox * p * 1.15, 0, 1);
      startTinnitus(t + 0.02, prox * p);
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Ambience                                                               */
  /* ---------------------------------------------------------------------- */

  const ambNodes = [];

  function loopNoise(buf, playRate) {
    const s = ctx.createBufferSource();
    s.buffer = buf;
    s.loop = true;
    s.playbackRate.value = playRate || 1;
    ambNodes.push(s);
    return s;
  }

  function lfo(hz, depth, target, phaseType) {
    const o = ctx.createOscillator();
    o.type = phaseType || 'sine';
    o.frequency.value = hz;
    const g = ctx.createGain();
    g.gain.value = depth;
    o.connect(g);
    g.connect(target);
    ambNodes.push(o);
    return o;
  }

  let windLowGain = null;
  let windGustGain = null;

  function buildAmbience() {
    const windScale = clamp((ATMOSPHERE.windSpeed || 2) / 2, 0.5, 2.2);

    // Bed 1 — the low body of the wind. Slow filter movement, wide and quiet.
    const low = loopNoise(bufPink, 0.85);
    const lowLP = ctx.createBiquadFilter();
    lowLP.type = 'lowpass';
    lowLP.frequency.value = 260 * windScale;
    lowLP.Q.value = 0.8;
    const lowPan = ctx.createStereoPanner ? ctx.createStereoPanner() : ctx.createGain();
    if (lowPan.pan) lowPan.pan.value = -0.35;
    windLowGain = ctx.createGain();
    windLowGain.gain.value = 0.085;
    low.connect(lowLP);
    lowLP.connect(lowPan);
    lowPan.connect(windLowGain);
    windLowGain.connect(ambienceBus);
    lfo(0.037, 130 * windScale, lowLP.frequency).start();
    lfo(0.011, 0.030, windLowGain.gain).start();

    // Bed 2 — gusts moving through wire, fencing and open container doors.
    const gust = loopNoise(bufWhite, 1.0);
    const gustBP = ctx.createBiquadFilter();
    gustBP.type = 'bandpass';
    gustBP.frequency.value = 780 * windScale;
    gustBP.Q.value = 1.15;
    const gustPan = ctx.createStereoPanner ? ctx.createStereoPanner() : ctx.createGain();
    if (gustPan.pan) gustPan.pan.value = 0.4;
    windGustGain = ctx.createGain();
    windGustGain.gain.value = 0.020;
    gust.connect(gustBP);
    gustBP.connect(gustPan);
    gustPan.connect(windGustGain);
    windGustGain.connect(ambienceBus);
    lfo(0.053, 420 * windScale, gustBP.frequency).start();
    lfo(0.019, 0.016, windGustGain.gain).start();
    lfo(0.007, 0.011, windGustGain.gain, 'triangle').start();

    // Bed 3 — sub rumble. A city that has been shelled has a floor tone.
    const rum = loopNoise(bufPink, 0.35);
    const rumLP = ctx.createBiquadFilter();
    rumLP.type = 'lowpass';
    rumLP.frequency.value = 92;
    rumLP.Q.value = 0.6;
    const rumG = ctx.createGain();
    rumG.gain.value = 0.10;
    rum.connect(rumLP);
    rumLP.connect(rumG);
    rumG.connect(ambienceBus);
    lfo(0.023, 26, rumLP.frequency).start();

    for (const n of ambNodes) {
      if (n.buffer && typeof n.start === 'function') {
        try {
          n.start(0, rnd() * (n.buffer.duration - 0.1));
        } catch {
          /* already started */
        }
      }
    }
  }

  /** Distant battle: someone else's war, two streets over. */
  let battleTimer = 3 + rnd() * 4;

  function distantBattle(t) {
    // Somewhere out past the map edge, at a plausible bearing.
    const ang = rnd() * Math.PI * 2;
    const r = 95 + rnd() * 80;
    _battlePos.set(_earPos.x + Math.cos(ang) * r, _earPos.y + 6 + rnd() * 20, _earPos.z + Math.sin(ang) * r);

    const roll = rnd();
    if (roll < 0.55) {
      // A burst of small arms, heavily filtered by distance.
      const n = 3 + ((rnd() * 5) | 0);
      const gap = 0.055 + rnd() * 0.05;
      const key = rnd() < 0.4 ? 'smg' : 'rifle';
      for (let i = 0; i < n; i++) playGun(key, t + i * gap * jit(0.15), _battlePos, 0.26 * jit(0.12), false);
    } else if (roll < 0.82) {
      // A single heavy report.
      playGun('dmr', t, _battlePos, 0.30 * jit(0.1), false);
    } else {
      // Ordnance. No transient survives that distance — just the low collapse.
      const ch = routeAt(_battlePos, t, 3.0, { wet: 2.0, tailGain: 2.0 });
      if (ch) {
        burst(ch.input, t, 'lowpass', 520, 120, 1.0, 0.34, 0.020, 0.9, bufPink, 1);
        tone(ch.input, t, 'sine', 74, 24, 1.1, 0.22, 0.020);
        burst(ch.tailIn, t, 'lowpass', 700, 200, 0.8, 0.7, 0.015, 1.4, bufPink, 1);
      }
    }
  }

  /* ---------------------------------------------------------------------- */
  /* One-shot dispatch                                                      */
  /* ---------------------------------------------------------------------- */

  /**
   * Several sibling modules both emit an event *and* call `playOneShot` for the same beat
   * (controller.js does exactly that for footsteps; weapon.js for reload phases). Rather
   * than pick a winner and break whichever module changes, both paths funnel through here
   * and a short gate drops the duplicate.
   */
  const lastAt = new Map();
  function gate(key, window) {
    const t = ctx.currentTime;
    const prev = lastAt.get(key);
    if (prev !== undefined && t - prev < window) return false;
    lastAt.set(key, t);
    return true;
  }

  function readPos(opts) {
    if (!opts) return null;
    const p = opts.position || opts.point || opts.pos;
    if (!p) return null;
    if (typeof p.x === 'number') {
      _tmpVec.set(p.x, p.y, p.z);
      return _tmpVec;
    }
    if (Array.isArray(p) && p.length >= 3) {
      _tmpVec.set(p[0], p[1], p[2]);
      return _tmpVec;
    }
    return null;
  }

  function startTime(opts) {
    // 2 ms of scheduling headroom keeps automation off the past, which some engines drop.
    const base = ctx.currentTime + 0.002;
    const d = opts && opts.delay ? opts.delay : 0;
    return base + d;
  }

  function playOneShot(name, opts) {
    if (disposed || !running || muted) return;
    if (!name) return;
    let t;
    let pos;
    try {
      t = startTime(opts);
      pos = readPos(opts);
    } catch {
      return;
    }
    const vol = opts && opts.volume !== undefined ? opts.volume : 1;
    const wid = (opts && (opts.weapon || opts.weaponId)) || null;
    const weaponId = wid && typeof wid === 'object' ? wid.id : wid;

    try {
      switch (name) {
        /* --- weapon report ------------------------------------------------ */
        case 'rifle':
        case 'smg':
        case 'dmr':
          if (!gate('gun', 0.012)) return;
          playGun(name, t, pos, vol, !pos);
          if (quality !== 'low') scheduleCasing(t, pos, weaponId);
          break;
        case 'shot':
        case 'fire':
          if (!gate('gun', 0.012)) return;
          playGun(GUN_ALIAS[weaponId] || 'rifle', t, pos, vol, !pos);
          break;
        case 'enemyShot':
          playGun(GUN_ALIAS[weaponId] || 'rifle', t, pos, vol * 0.95, false);
          break;

        /* --- mechanical --------------------------------------------------- */
        case 'magout':
        case 'magin':
        case 'boltback':
        case 'boltrelease':
        case 'boltlock':
        case 'dryfire':
        case 'trigger':
        case 'weaponraise':
        case 'weaponlower':
        case 'inspect':
        case 'adsin':
        case 'adsout':
          if (!gate(name, 0.045)) return;
          playMech(name, t, weaponId);
          break;
        case 'enemyReload':
          if (!gate('enemyReload', 0.12)) return;
          playEnemyReload(t, pos, vol);
          break;
        case 'casing':
        case 'brass':
          if (!gate('casing', 0.020)) return;
          playCasing(t, pos, vol * 0.55, weaponId);
          break;

        /* --- movement ----------------------------------------------------- */
        case 'footstep':
          if (!gate('footstep', 0.055)) return;
          playFootstep(opts?.surface || 'concrete', t, pos, vol, opts?.speed, false);
          break;
        case 'land':
          if (!gate('footstep', 0.055)) return;
          playFootstep(opts?.surface || 'concrete', t, pos, vol * 1.2, 6, true);
          break;
        case 'jump':
          if (!gate('jump', 0.10)) return;
          playJump(t, opts?.surface || 'concrete', vol);
          break;
        case 'slide':
          if (!gate('slide', 0.20)) return;
          playSlide(t, opts?.surface || 'concrete', vol);
          break;
        case 'mantle':
          if (!gate('mantle', 0.20)) return;
          playMantle(t, opts?.surface || 'concrete', vol);
          break;
        case 'cloth':
          selfCloth(t, vol * 0.5);
          break;

        /* --- impacts ------------------------------------------------------ */
        case 'impact':
          playImpact(opts?.surface || 'concrete', t, pos, vol);
          break;
        case 'impactConcrete':
        case 'impactMetal':
        case 'impactWood':
        case 'impactDirt':
        case 'impactGravel':
        case 'impactGlass':
        case 'impactSandbag':
        case 'impactFlesh':
          playImpact(name.slice(6).toLowerCase(), t, pos, vol);
          break;

        /* --- combat feedback ---------------------------------------------- */
        case 'whizz':
          if (!gate('whizz', 0.030)) return;
          playWhizz(t, pos, vol);
          break;
        case 'hitmarker':
        case 'hit':
          playTick(t, 'body');
          break;
        case 'hitHead':
        case 'headshot':
          playTick(t, 'head');
          break;
        case 'kill':
        case 'killConfirm':
          playTick(t, 'kill');
          break;
        case 'enemyHit':
          playFleshHit(t, pos, vol, false);
          break;
        case 'enemyHitHead':
          playFleshHit(t, pos, vol, true);
          break;
        case 'enemyDeath':
          playDeath(t, pos, vol);
          break;
        case 'playerHurt':
        case 'damage':
          if (!gate('hurt', 0.09)) return;
          playHurt(t, opts?.amount);
          break;
        case 'heartbeat':
          playHeartbeat(t, vol);
          break;
        case 'explosion':
          playExplosion(t, pos, opts?.power, opts?.radius);
          break;

        /* --- UI ----------------------------------------------------------- */
        case 'uiHover':
          playUI(t, 1500, 0.018, 0.030);
          break;
        case 'uiClick':
          playUI(t, 900, 0.040, 0.055);
          break;
        case 'uiBack':
          playUI(t, 620, 0.038, 0.070);
          break;
        case 'lowAmmo':
          playUI(t, 2100, 0.030, 0.045);
          break;
        default:
          // Unknown name: stay quiet rather than guessing. Not an error.
          break;
      }
    } catch {
      // A single failed voice must never stall the mixer or the frame.
    }
  }

  /** Brass leaves the port a beat after the shot and lands a beat after that. */
  function scheduleCasing(t, pos, weaponId) {
    playCasing(t + 0.30 + rnd() * 0.20, pos, 0.28, weaponId);
  }

  function playEnemyReload(t, pos, vol) {
    const ch = routeAt(pos, t, 1.2, { wet: 0.8 });
    if (!ch) return;
    const d = ch.input;
    const v = vol === undefined ? 0.5 : vol;
    transient(d, t, 2600, 2.0, 0.16 * v, 0.002);
    burst(d, t + 0.04, 'bandpass', 700, 420, 2.2, 0.14 * v, 0.004, 0.070, bufPink, 1);
    burst(d, t + 0.46, 'lowpass', 520, 250, 2.4, 0.22 * v, 0.0014, 0.060, bufWhite, 1);
    transient(d, t + 0.78, 3600, 1.6, 0.20 * v, 0.002);
    ring(d, t + 0.78, 2200, 0.11, 0.07 * v, 2, 0.05);
  }

  function playJump(t, surface, vol) {
    const ch = routeAt(null, t, 0.4, { wet: 0.4 });
    if (!ch) return;
    const F = FOOT[surface] || FOOT.concrete;
    const v = (vol === undefined ? 0.55 : vol) * jit(0.08);
    // Push-off scuff, then kit settling.
    burst(ch.input, t, 'bandpass', F.slap * 0.8, F.slap * 0.35, 1.2, 0.24 * v, 0.004, 0.075, bufBright, 1);
    burst(ch.input, t, 'lowpass', F.thud * 0.9, F.thud * 0.4, 1.6, 0.30 * v, 0.003, 0.060, bufPink, 1);
    playCloth(ch.input, t + 0.01, 0.55 * v);
  }

  function playSlide(t, surface, vol) {
    const ch = routeAt(null, t, 1.3, { wet: 0.7 });
    if (!ch) return;
    const F = FOOT[surface] || FOOT.concrete;
    const v = (vol === undefined ? 0.9 : vol) * jit(0.06);
    // Long grinding sweep: the filter opens then closes as the slide bleeds off.
    burst(ch.input, t, 'bandpass', F.slap * 1.1, F.slap * 0.25, 0.9, 0.42 * v, 0.030, 0.70, bufWhite, jit(0.1));
    burst(ch.input, t, 'lowpass', 300, 130, 1.4, 0.34 * v, 0.020, 0.80, bufPink, 1);
    if (quality !== 'low' && (surface === 'gravel' || surface === 'dirt')) {
      burst(ch.input, t + 0.02, 'bandpass', 2400, 1200, 1.0, 0.22 * v, 0.020, 0.60, bufGrain, 1.5);
    }
    playCloth(ch.input, t, 0.9 * v);
  }

  function playMantle(t, surface, vol) {
    const ch = routeAt(null, t, 0.9, { wet: 0.5 });
    if (!ch) return;
    const v = (vol === undefined ? 0.8 : vol) * jit(0.06);
    playCloth(ch.input, t, 1.0 * v);
    // Hands on the ledge, then boots.
    burst(ch.input, t + 0.06, 'bandpass', 1100, 600, 1.6, 0.20 * v, 0.008, 0.12, bufPink, 1);
    playFootstep(surface, t + 0.34, null, v * 0.7, 3, false);
  }

  function playHeartbeat(t, vol) {
    const ch = routeAt(null, t, 0.9, { wet: 0.1 });
    if (!ch) return;
    const v = (vol === undefined ? 0.5 : vol);
    tone(ch.input, t, 'sine', 58, 34, 0.115, 0.42 * v, 0.008);
    tone(ch.input, t + 0.20, 'sine', 50, 30, 0.145, 0.30 * v, 0.010);
  }

  function playUI(t, f, dur, dec) {
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(0.10, t + 0.002);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur + dec);
    g.gain.setValueAtTime(0, t + dur + dec + 0.002);
    g.connect(uiBus);
    const o = ctx.createOscillator();
    o.type = 'triangle';
    o.frequency.setValueAtTime(f, t);
    o.frequency.exponentialRampToValueAtTime(f * 0.86, t + dur + dec);
    o.connect(g);
    track(o);
    try {
      o.start(t);
      o.stop(t + dur + dec + 0.03);
    } catch {
      liveVoices--;
    }
  }

  /* ---------------------------------------------------------------------- */
  /* Event wiring                                                           */
  /* ---------------------------------------------------------------------- */

  const unsubs = [];
  function on(name, fn) {
    const ev = game && game.events;
    if (!ev || typeof ev.on !== 'function') return;
    const off = ev.on(name, fn);
    unsubs.push(typeof off === 'function' ? off : () => ev.off?.(name, fn));
  }

  on('shot', (p) => {
    if (!p) return;
    const key = (p.weapon && (p.weapon.audio?.fire || GUN_ALIAS[p.weapon.id])) || 'rifle';
    playOneShot(GUNS[key] ? key : 'rifle', { volume: 1, weapon: p.weapon });
  });

  on('impact', (p) => {
    if (!p) return;
    // Impacts arrive in bursts; the ear cannot resolve more than a few per 20 ms anyway.
    if (!gate('impact', 0.014)) return;
    playOneShot('impact', { position: p.point, surface: p.surface, volume: p.fromPlayer === false ? 0.85 : 1 });
  });

  on('hit', (p) => {
    if (!p) return;
    playTick(startTime(null), p.headshot ? 'head' : 'body');
  });

  on('kill', () => {
    playTick(startTime(null) + 0.06, 'kill');
  });

  on('damage', (p) => {
    if (!gate('hurt', 0.09)) return;
    playHurt(startTime(null), p && p.amount);
  });

  on('reload', (p) => {
    if (!p) return;
    const wid = p.weapon && p.weapon.id;
    if (p.phase === 'magout') playOneShot('magout', { weapon: wid });
    else if (p.phase === 'magin') playOneShot('magin', { weapon: wid });
    else if (p.phase === 'end' && p.empty) playOneShot('boltrelease', { weapon: wid });
    else if (p.phase === 'start') selfCloth(startTime(null), 0.35);
  });

  on('ads', (p) => {
    playOneShot(p && p.active ? 'adsin' : 'adsout', { weapon: p && p.weapon && p.weapon.id });
  });

  on('footstep', (p) => {
    if (!p) return;
    playOneShot('footstep', { surface: p.surface, volume: 0.55, speed: p.speed });
  });

  on('whizz', (p) => {
    if (!p) return;
    playOneShot('whizz', { position: p.point, volume: 0.7 });
  });

  on('explosion', (p) => {
    if (!p) return;
    playOneShot('explosion', { position: p.point, power: p.power, radius: p.radius });
  });

  /* ---------------------------------------------------------------------- */
  /* Transport                                                              */
  /* ---------------------------------------------------------------------- */

  let running = false;
  let muted = false;
  let volume = 0.7;
  let ambienceBuilt = false;

  function applyGain() {
    const target = muted ? 0 : volume;
    try {
      const t = ctx.currentTime;
      masterGain.gain.cancelScheduledValues(t);
      masterGain.gain.setTargetAtTime(target, t, 0.03);
    } catch {
      masterGain.gain.value = target;
    }
  }

  function resume() {
    if (disposed) return;
    try {
      if (ctx.state === 'suspended') ctx.resume();
    } catch {
      /* blocked; try again on the next gesture */
    }
    if (ctx.state === 'running') {
      running = true;
      if (!ambienceBuilt) {
        ambienceBuilt = true;
        try {
          buildAmbience();
        } catch {
          /* ambience is optional; the game must still make noise */
        }
      }
      try {
        ambienceBus.gain.setTargetAtTime(muted ? 0 : 1, ctx.currentTime, 1.2);
      } catch {
        ambienceBus.gain.value = muted ? 0 : 1;
      }
      detachGestures();
    }
  }

  const GESTURES = ['pointerdown', 'mousedown', 'keydown', 'touchstart'];
  const onGesture = () => resume();
  function attachGestures() {
    for (const g of GESTURES) window.addEventListener(g, onGesture, { passive: true });
  }
  function detachGestures() {
    for (const g of GESTURES) window.removeEventListener(g, onGesture);
  }
  attachGestures();
  // Some browsers hand us a running context immediately (autoplay already granted).
  if (ctx.state === 'running') resume();

  const onVisibility = () => {
    if (disposed) return;
    try {
      if (document.hidden) ctx.suspend();
      else if (running) ctx.resume();
    } catch {
      /* ignore */
    }
  };
  document.addEventListener('visibilitychange', onVisibility);

  /* ---------------------------------------------------------------------- */
  /* Per-frame update                                                       */
  /* ---------------------------------------------------------------------- */

  let raycastTimer = 0;
  let ambienceMode = 1;

  function update(dt, g) {
    if (disposed) return;
    const gm = g || game;
    dt = clamp(dt || 0, 0, 1 / 20);
    if (!running) {
      // Keep trying: a pointer-lock click may resume the context without a listener firing.
      if (ctx.state === 'running') resume();
      return;
    }
    const t = ctx.currentTime;

    /* --- listener pose ---------------------------------------------------- */
    const cam = gm && gm.camera;
    if (cam) {
      const m = cam.matrixWorld.elements;
      _earPos.set(m[12], m[13], m[14]);
      // Three's camera looks down -Z; the basis is columns 0..2 of the world matrix.
      _earFwd.set(-m[8], -m[9], -m[10]);
      _earUp.set(m[4], m[5], m[6]);
      const L = ctx.listener;
      if (L) {
        if (L.positionX) {
          // setTargetAtTime rather than a hard set: a 400 deg/s flick otherwise zippers the
          // HRTF convolution audibly.
          L.positionX.setTargetAtTime(_earPos.x, t, 0.014);
          L.positionY.setTargetAtTime(_earPos.y, t, 0.014);
          L.positionZ.setTargetAtTime(_earPos.z, t, 0.014);
          L.forwardX.setTargetAtTime(_earFwd.x, t, 0.014);
          L.forwardY.setTargetAtTime(_earFwd.y, t, 0.014);
          L.forwardZ.setTargetAtTime(_earFwd.z, t, 0.014);
          L.upX.setTargetAtTime(_earUp.x, t, 0.014);
          L.upY.setTargetAtTime(_earUp.y, t, 0.014);
          L.upZ.setTargetAtTime(_earUp.z, t, 0.014);
        } else if (L.setPosition) {
          L.setPosition(_earPos.x, _earPos.y, _earPos.z);
          L.setOrientation(_earFwd.x, _earFwd.y, _earFwd.z, _earUp.x, _earUp.y, _earUp.z);
        }
      }
    }

    /* --- indoor / outdoor ------------------------------------------------- */
    raycastTimer -= dt;
    if (raycastTimer <= 0) {
      raycastTimer = 0.2;
      let enclosed = 0;
      const lvl = gm && gm.level;
      if (lvl && typeof lvl.raycast === 'function') {
        _rayOrigin.copy(_earPos);
        _rayOrigin.y += 0.15;
        let h = null;
        try {
          h = lvl.raycast(_rayOrigin, _rayUp, 26) || null;
        } catch {
          h = null;
        }
        // Closer ceiling → tighter room → more of the short IR.
        if (h) enclosed = clamp(1.15 - (h.distance || 6) / 16, 0.35, 1);
      }
      indoorTarget = enclosed;
    }
    indoor += (indoorTarget - indoor) * (1 - Math.exp(-2.6 * dt));

    returnFar.gain.value = 0.62 + (1 - indoor) * 0.45;
    returnClose.gain.value = 0.06 + indoor * 0.70;
    // A hard interior is brighter close in; the yard tail is dustier.
    sendFarIn.frequency.value = 4200 - indoor * 900;
    sendCloseIn.frequency.value = 5200 + indoor * 1800;

    /* --- concussion recovery ---------------------------------------------- */
    if (ducking > 0.0005) {
      // ~2.5 s to functionally clear; exponential so the first second is the dramatic part.
      ducking *= Math.exp(-dt * 1.65);
      if (ducking < 0.0005) ducking = 0;
      duckGain.gain.value = 1 - ducking * 0.84;
      duckLP.frequency.value = 20000 * Math.pow(0.035, ducking);
    } else if (duckGain.gain.value !== 1) {
      duckGain.gain.value = 1;
      duckLP.frequency.value = 20000;
    }

    /* --- ambience --------------------------------------------------------- */
    const playing = gm && gm.state && gm.state.mode === 'playing';
    const wantAmb = playing ? 1 : 0.55;
    ambienceMode += (wantAmb - ambienceMode) * (1 - Math.exp(-1.2 * dt));
    ambienceBus.gain.value = muted ? 0 : ambienceMode;

    battleTimer -= dt;
    if (battleTimer <= 0) {
      battleTimer = 3.5 + rnd() * 7.5;
      if (quality !== 'low' && playing) {
        try {
          distantBattle(t + 0.05);
        } catch {
          /* a missed distant burst is not worth a frame */
        }
      }
    }
  }

  let indoorTarget = 0;

  /* ---------------------------------------------------------------------- */
  /* Public surface                                                         */
  /* ---------------------------------------------------------------------- */

  const audio = {
    ctx,
    available: true,
    volume,
    resume,
    update,
    playOneShot,
    setVolume(v) {
      volume = clamp(typeof v === 'number' && isFinite(v) ? v : 0.7, 0, 1);
      audio.volume = volume;
      applyGain();
    },
    setMuted(m) {
      muted = !!m;
      applyGain();
      ambienceBus.gain.value = muted ? 0 : ambienceMode;
    },
    setQuality(q) {
      if (typeof q === 'string') {
        quality = q;
        sizePools();
      }
    },
    /** Debug/diagnostic surface — safe to read, not part of the contract. */
    stats: {
      get voices() {
        return liveVoices;
      },
      get indoor() {
        return indoor;
      },
      get ducking() {
        return ducking;
      },
    },
    dispose() {
      if (disposed) return;
      disposed = true;
      running = false;
      detachGestures();
      document.removeEventListener('visibilitychange', onVisibility);
      for (const off of unsubs) {
        try {
          off();
        } catch {
          /* already gone */
        }
      }
      unsubs.length = 0;
      for (const n of ambNodes) {
        try {
          n.stop();
        } catch {
          /* not a source */
        }
        try {
          n.disconnect();
        } catch {
          /* ignore */
        }
      }
      ambNodes.length = 0;
      for (const o of [tinnitusOsc, tinnitusOsc2]) {
        try {
          o && o.stop();
        } catch {
          /* ignore */
        }
      }
      tinnitusOsc = null;
      tinnitusOsc2 = null;
      try {
        masterGain.disconnect();
      } catch {
        /* ignore */
      }
      try {
        ctx.close();
      } catch {
        /* ignore */
      }
    },
  };

  // `muted` is documented as a plain field, so expose it as one but keep the gain in sync.
  Object.defineProperty(audio, 'muted', {
    get: () => muted,
    set: (m) => audio.setMuted(m),
    enumerable: true,
  });

  applyGain();
  return audio;
}

export default createAudio;
